# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='email',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='email',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Endereco'),
            preserve_default=False,
        ),
    ]
