# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item_pedido_produto_unidade_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(default=0, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='foto',
            field=models.ImageField(blank=True, default='cliente/no_foto.jpg', null=True, upload_to='cliente/'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.IntegerField(default=0, verbose_name='telefone'),
        ),
    ]
