# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160528_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_parcela', models.IntegerField(default=0, verbose_name='quantidade_parcela')),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.IntegerField(default=0, verbose_name='parcela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo ?'),
        ),
    ]
