# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160528_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='entidade',
            field=models.CharField(default=1, max_length=30, verbose_name='entidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produto',
            field=models.CharField(default=1, max_length=30, verbose_name='nome'),
            preserve_default=False,
        ),
    ]
