# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160528_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro',
            name='parcela',
        ),
        migrations.AddField(
            model_name='venda',
            name='financeiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Financeiro'),
            preserve_default=False,
        ),
    ]
